<?php 
/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SpoonacularAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Classifiedproduct implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var array $breadcrumbs public property
     */
    public $breadcrumbs;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $category public property
     */
    public $category;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $cleanTitle public property
     */
    public $cleanTitle;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $usdaCode public property
     */
    public $usdaCode;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $breadcrumbs   Initialization value for the property $this->breadcrumbs
     * @param   string            $category      Initialization value for the property $this->category   
     * @param   string            $cleanTitle    Initialization value for the property $this->cleanTitle 
     * @param   integer           $usdaCode      Initialization value for the property $this->usdaCode   
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->breadcrumbs = func_get_arg(0);
            $this->category    = func_get_arg(1);
            $this->cleanTitle  = func_get_arg(2);
            $this->usdaCode    = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['breadcrumbs'] = $this->breadcrumbs;
        $json['category']    = $this->category;
        $json['cleanTitle']  = $this->cleanTitle;
        $json['usdaCode']    = $this->usdaCode;

        return $json;
    }
}