<?php 
/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SpoonacularAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class FindByIngredientsModel implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $image public property
     */
    public $image;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $likes public property
     */
    public $likes;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $missedIngredientCount public property
     */
    public $missedIngredientCount;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $usedIngredientCount public property
     */
    public $usedIngredientCount;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $id                      Initialization value for the property $this->id                   
     * @param   string            $image                   Initialization value for the property $this->image                
     * @param   integer           $likes                   Initialization value for the property $this->likes                
     * @param   integer           $missedIngredientCount   Initialization value for the property $this->missedIngredientCount
     * @param   string            $title                   Initialization value for the property $this->title                
     * @param   integer           $usedIngredientCount     Initialization value for the property $this->usedIngredientCount  
     */
    public function __construct()
    {
        if(6 == func_num_args())
        {
            $this->id                    = func_get_arg(0);
            $this->image                 = func_get_arg(1);
            $this->likes                 = func_get_arg(2);
            $this->missedIngredientCount = func_get_arg(3);
            $this->title                 = func_get_arg(4);
            $this->usedIngredientCount   = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                    = $this->id;
        $json['image']                 = $this->image;
        $json['likes']                 = $this->likes;
        $json['missedIngredientCount'] = $this->missedIngredientCount;
        $json['title']                 = $this->title;
        $json['usedIngredientCount']   = $this->usedIngredientCount;

        return $json;
    }
}