<?php 
/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SpoonacularAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Productjson implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @maps plu_code
     * @var string $pluCode public property
     */
    public $pluCode;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $upc public property
     */
    public $upc;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $pluCode    Initialization value for the property $this->pluCode 
     * @param   string            $title      Initialization value for the property $this->title   
     * @param   string            $upc        Initialization value for the property $this->upc     
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->pluCode  = func_get_arg(0);
            $this->title    = func_get_arg(1);
            $this->upc      = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['plu_code'] = $this->pluCode;
        $json['title']    = $this->title;
        $json['upc']      = $this->upc;

        return $json;
    }
}