<?php
/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SpoonacularAPILib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class. 
 */
class Configuration {
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'https://spoonacular-recipe-food-nutrition-v1.p.mashape.com';

    /**
     * The Mashape application you want to use for this session.
     * @var string
     */
    /**
     * @todo Replace the $xMashapeKey with an appropriate value
     */
    public static $xMashapeKey = 'TODO: Replace';

}
